voter_gpt_4_1_mini_temp_0.7:
  api_key_id: 'genplat'
  model: 'gpt-4.1-mini'
  temperature: 0.7
voter_o3_mini_temp_0.7:
  api_key_id: 'genplat'
  model: 'o3-mini'
  temperature: 0.7
voter_o3_temp_0.7:
  api_key_id: 'genplat'
  model: 'o3'
  temperature: 0.7
voter_gpt_4_1_mini_temp_0.5:
  api_key_id: 'genplat'
  model: 'gpt-4.1-mini'
  temperature: 0.5
voter_o3_mini_temp_0.5:
  api_key_id: 'genplat'
  model: 'o3-mini'
  temperature: 0.5
voter_o3_temp_0.5:
  api_key_id: 'genplat'
  model: 'o3'
  temperature: 0.5
voter_gpt_4_1_mini_temp_1.2:
  api_key_id: 'genplat'
  model: 'gpt-4.1-mini'
  temperature: 1.2
voter_o3_mini_temp_1.2:
  api_key_id: 'genplat'
  model: 'o3-mini'
  temperature: 1.2
voter_o3_temp_1.2:
  api_key_id: 'genplat'
  model: 'o3'
  temperature: 1.2