import pydantic
from pydantic import Field


class JudgeResponse(pydantic.BaseModel):
    """
    Response model for the judge voter.
    """

    category_id: str = Field(description="The category identifier (id)")
    nominee_id: str = Field(description="The nominee identifier (id)")
    decision: str = Field(description="The decision for why you chose the nominee")


def get_judge_voter_prompt(categories: list[dict], votes: list[dict]) -> dict[str, str]:
    """
    Build prompts for the judge voter.

    Parameters
    ----------
    categories : list[dict]
        All Oscar categories included in the ballot.
    votes : list[dict]
        Aggregated votes generated by expert voters.

    Returns
    -------
    dict[str, str]
        Prompt dictionary with `system_prompt` and `user_prompt`.
    """

    system_prompt = """
    You are a movie expert who helps people vote for the best movies and actors in the Academy Awards.
    You are given a list of votes from other movie expert voters who have voted for the best nominee in each category
    and their explanations for why they chose the nominee.
    Based on the expert votes, you need to decide
    which is the best nominee in each category
    and explain why you chose the nominee.

    You must return a json of the best nominee in each category
    in the following JSON format:
    {"votes":[{"category_id":"<CATEGORY_ID>","nominee_id":"<NOMINEE_ID>","decision":"<decision>"}]}

    The explanation should be a short decision explanation (no more than 100 words) of why you chose the nominee,
    pointing out the reasons why you chose the nominee.
    """

    user_prompt = """
    Help me decide which is the best nominee in the following categories:
    """

    category_prompt = ""
    for category in categories:
        category_prompt += f"""
        <CATEGORY>
            <CATEGORY_ID>{category['id']}</CATEGORY_ID>
            <NAME>{category['name']}</NAME>
            <DESCRIPTION>{category['description']}</DESCRIPTION>
        </CATEGORY>
        """

    expert_votes_prompt = ""
    for vote in votes:
        expert_votes_prompt += f"""
        <VOTE>
            <CATEGORY_ID>{vote['category_id']}</CATEGORY_ID>
            <NOMINEE_ID>{vote['nominee_id']}</NOMINEE_ID>
            <EXPLANATION>{vote['explanation']}</EXPLANATION>
        </VOTE>
        """

    user_prompt += f"""
    The categories are as follows:
    {category_prompt}

    The expert votes so far are as follows:
    {expert_votes_prompt}
    """

    return {
        "system_prompt": system_prompt.strip(),
        "user_prompt": user_prompt.strip(),
    }
